name: test-setup-python

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://jbencook/cml:latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache      
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Display Python version
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache            
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache            
        run: |
          python -m pip install --upgrade pip 
          pip install sklearn
