name: test-setup-python

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://jbencook/cml:latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Display Python version
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
        run: touch foobar.txt

      - name: Is it there
        run: ls
