name: test-setup-python

on: [push]

jobs:
  run:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2

      - name: Environment
        run: env
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install sklearn
