name: test-setup-python

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://jbencook/cml:latest
    env:
      AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

    steps:
      - name: Environment
        run: |
          env
          pwd
          ls /
          ls /opt/
